=== Praktikum-PvAS/process-historian/src/json_schemata/opcua_config_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "required": ["host", "actuators", "sensors", "services"],
  "properties": {
    "host": {
      "type": "string",
      "format": "uri",
      "minLength": 1
    },
    "actuators": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/assemblyType"
      }
    },
    "sensors": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/assemblyType"
      }
    },
    "services": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/assemblyType"
      }
    }
  },
  "$defs": {
    "assemblyType": {
      "type": "object",
      "required": [
        "id",
        "attributes"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "attributes": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/assemblyAttr"
          }
        }
      }
    },
    "assemblyAttr": {
      "type": "object",
      "required": ["interval", "name", "namespace", "node_identifier"],
      "properties": {
        "interval": {
          "type": "number",
          "multipleOf": 1.0,
          "minimum": 1
        },
        "mode": {
          "enum": [
            "poll",
            "subscription"
          ],
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "namespace": {
          "type": "string"
        },
        "node_identifier": {
          "type": "string"
        }
      }
    }
  },
  "type": "object"
}

=== Praktikum-PvAS/process-historian/src/tests/opcua_config.json
{
  "host": "opc.tcp://127.0.0.1:53530/OPCUA/SimulationServer",
  "actuators": [
    {
      "id": "test_id",
      "attributes": [
        {
          "interval": 1000,
          "mode": "poll",
          "name": "value_1",
          "namespace": "http://examples.freeopcua.github.io",
          "node_identifier": "i=1012"
        }
      ]
    },
    {
      "id": "test_id_2",
      "attributes": [
        {
          "interval": 1000,
          "mode": "poll",
          "name": "value_2",
          "namespace": "http://examples.freeopcua.github.io",
          "node_identifier": "i=1010"
        },
        {
          "interval": 1000,
          "mode": "subscription",
          "name": "value_3",
          "namespace": "http://examples.freeopcua.github.io",
          "node_identifier": "i=1011"
        }
      ]
    }
  ],
  "sensors": [],
  "services": []
}
